apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |+
    alertmanagerMain:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    prometheusK8s:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    prometheusOperator:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    k8sPrometheusAdapter:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    kubeStateMetrics:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    telemeterClient:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    openshiftStateMetrics:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/infra: ""
    thanosQuerier:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
      nodeSelector:
        node-role.kubernetes.io/infra: ""