apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: custom-efrmsfduat
  namespace: openshift-ingress-operator
spec:
  domain: sasviya.efrmsfduat.idbibank.com
  defaultCertificate:
    name: custom-ingress-custom-certs
  replicas: 2
  namespaceSelector:
    matchLabels:
      type: sharded
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
  endpointPublishingStrategy:
    type: NodePortService
    nodePort:
      protocol: TCP