apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-cas
  namespace: openshift-config
data:
  default-route-openshift-image-registry.apps.efrmsfduat.idbibank.com: |
    -----BEGIN CERTIFICATE-----
    MIIDczCCAlugAwIBAgIIJyLz56jgi6YwDQYJKoZIhvcNAQELBQAwJjEkMCIGA1UE
    AwwbaW5ncmVzcy1vcGVyYXRvckAxNzUxODk5MzE2MB4XDTI1MDcwNzE0NDE1NloX
    DTI3MDcwNzE0NDE1N1owKTEnMCUGA1UEAwweKi5hcHBzLmVmcm1zZmR1YXQuaWRi
    aWJhbmsuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvPu410Po
    TFsQzBzX8tTF83icbdNRbvAo/Oz9CacWlrRdXLiptm7l1SCOJSZBXPcmEwBT2jcn
    KOhPQ4+VoeIPQ/I3r/c3n+mkFVefRpJgQHmroyfpXjL5z+lhkH4NG4oqrDxV2GYN
    S1UQgl+d/z+C774y2fNzIlUT6jAzfKlJUzU1ZpXUnCPfJtWJ5yQV5yd4Mah0sH4Y
    MD/Th6/GUdoXFXqvAQ77Cwkkjtz9bPSNQVTKzmXbSjOYsm4+uHhWUOJF7qctxEvl
    0GNMAIV+BDYi8Y1iOSwJIxGaQzS4HVIc2N/6vVJfcpMHIRf2PRMev/UH/VwYLCv4
    dVUABIuIa/eSoQIDAQABo4GhMIGeMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAK
    BggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRNp8CuwFZFxv+kYuqO
    4hB2JKxYqjAfBgNVHSMEGDAWgBSRxjkrGyz6A+iQA64d+VKcWL8mOzApBgNVHREE
    IjAggh4qLmFwcHMuZWZybXNmZHVhdC5pZGJpYmFuay5jb20wDQYJKoZIhvcNAQEL
    BQADggEBAKqzza5of3qwljqam+ccoL+Nv9oktFZFDow5VVNJ6bwc0WPFzPYZdlIL
    9v841VUOwj7RN4IXBh7OG4jDXXDtI2tpVwgeCXVUzZKKt7tpcZbreP2RqGc7QKq/
    SmpWwrTTaaRCS7IZCJMsbwAFQZ3VBhJllYng7YSMHuSCPJijkwfJ7hvu9AaTICvS
    KeM0XwFonKfTvL3Y8W+A/QtF/mHqklCTSzLRsPNbGyk6+CBKCK0/0CEqEcCdaXmz
    bkXTNYGV2Nn6taFDR54TQLQWRY3jjFfwSp+aFQ439z5qPSw6HyysGjVttje5K/5M
    jO39K9pVZ1IyMD17lT7XE7HuxkSwUaE=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDDDCCAfSgAwIBAgIBATANBgkqhkiG9w0BAQsFADAmMSQwIgYDVQQDDBtpbmdy
    ZXNzLW9wZXJhdG9yQDE3NTE4OTkzMTYwHhcNMjUwNzA3MTQ0MTU1WhcNMjcwNzA3
    MTQ0MTU2WjAmMSQwIgYDVQQDDBtpbmdyZXNzLW9wZXJhdG9yQDE3NTE4OTkzMTYw
    ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDGRdpT4ZQ0dmsPq2/Bj38E
    MVaQ6Yoln5ry5D+uX1uGFSiYrGRl35CtvUIVVftLjQwcIbWLGIS27+pE14l8RQH1
    TeGJ5eYtfawD18/rrT5YVvcdPWXoIom1gs5W3U879wIJCySUvI4PP05qTY1cmIUq
    j4fJljYqI7n3y2Gew4iB7dEu/xQaX8RE+PpzB5MGaR3QW6XiTjBuKdBL4k9Edrbx
    TALH0x+g9sp4JdPDSgaDgPWCiSOS+SJ3cp+azJYHy1yhLQ09SOBkUViyjYbMUUlE
    Ime8pdo5rXHSKNe1am3Tu0AdTpOoG6ssNBykOiQUcnWZFr4q0LPyU4h+xUX3ZRJr
    AgMBAAGjRTBDMA4GA1UdDwEB/wQEAwICpDASBgNVHRMBAf8ECDAGAQH/AgEAMB0G
    A1UdDgQWBBSRxjkrGyz6A+iQA64d+VKcWL8mOzANBgkqhkiG9w0BAQsFAAOCAQEA
    ePauUp4gxdB03fE2oG3S2YpQJEhFah4k3HiCTz3Ur95elbjcYnfF2gJnwMV59OmP
    NTde4lmvNs53SfdnRlTcQ6RG4fo0URuTing51vAy9rMV1hYh0V6mGRTD/ODBAnjn
    UDzix8a4DUEf35oxnXdOISRVOLNAtNcx7xngINm/AOv/u8ZPwZaXCeThU8iSAfG4
    e1auSGQQkFgFKV5U/pINGn8vEs0p90l+UWdqpI+Dg14Hgu+xf45rEQim4qC8cEEX
    D70xeSILj9VGMLv3aEgWVPbHQMcgJrVPgMuT7zOA6ozhG6q2As3gBFGI2LVUkN2+
    PRtkA0IZu4JoPfNbhIU9Og==
    -----END CERTIFICATE-----

 