kind: ImageSetConfiguration 
apiVersion: mirror.openshift.io/v1alpha2 
storageConfig: 
   local: 
      path: /ocpdata/ocp-packages/base-4.18.6/ ## please check this directordy path is avilable on the dowmloader, if not then create first. 
mirror: 
   platform: 
      channels: 
      - name: stable-4.18 
        type: ocp 
        minVersion: 4.18.6 
        maxVersion: 4.18.6 
      graph: true 
   additionalImages: 
   - name: registry.redhat.io/ubi9/ubi:latest 
   helm: {} 
