apiVersion: v1
kind: PersistentVolume
metadata:
name: image-registry-pv
spec:
capacity:
   storage: 475Gi
accessModes:
   - ReadWriteMany
persistentVolumeReclaimPolicy: Retain
storageClassName: nfs
nfs:
   path: /efrmsfduat-internalregistry
   server: 10.142.92.33